### ISSUE TITLE
What about desktop icons? Some sort of `pcmanfm --desktop`/`idesk` alternative for Wayland..?

### ISSUE THREAD

**Issue by xplshn** [System64fumo/sysshell#1]
Hi, awesome project, have you considered making a program for the very specific task of displaying desktop icons using xdg-layer-shell? I had made an initial implementation in Go, but it had issues and I really suck with GTK, mostly because I don't really like its bloat, and also because the bindings and the GTK docs weren't 100% clear at least for me. Anyways, thanks! Really cool stuff you're working on, hope you keep it minimal or make it even more minimal, both in terms of code, features and libraries used.

:)

**Comment by System64fumo** [comment]
Hello, Apologies for the late response i was on holiday.
I'm assuming you mean something sort of overlay that shows ~/Desktop but as a layer shell correct?

Personally not a fan of desktop icons but this is very easily doable, Good suggestion!

**Comment by System64fumo** [comment]
Wish granted!

I kind of forgot that file managers could be used as desktops and wasted an hour or two adding this to sysshell but then i remembered that i have my very own file manager that i started developing for fun a while back.

I've added a -d launch flag to enable desktop mode in [Frog](https://github.com/System64fumo/frog)
Hope this is what you were asking for!

**Comment by xplshn** [comment]
Thanks mate! Awesome stuff you're doing! A truly modular desktop, I love it! (even if its GTK, this is lovely)

**Comment by System64fumo** [comment]
No problem, I would have rathered QT but after looking at how hard styling it can be & how annoying the build system is & ram usage i decided to stick with GTK :|

**Comment by xplshn** [comment]
Yeah, I don't like neither, I prefer FLTK and smaller ones, but I get it, GTK is pretty and it is convenient, most people don't care about making statically linked versions of their programs or about having free licensing (ie, MIT-0, 3BSD, etc)A

Anyways, thanks for the awesome bytes! Going to integrate this into my Sway config and setup soon, lovely stuff!
