### ISSUE TITLE
Section 'main' not found

### ISSUE THREAD

**Issue by who53** [System64fumo/sysshell#2]

**Comment by System64fumo** [comment]
Weird.. I thought i fixed this a few days back?
You sure you're on the newest version?

Do you have either ~/.config/sys64/shell/config.conf
Or /usr/share/sys64/shell/config.conf?

**Comment by who53** [comment]
Oh, I didn't had the conf file at the right place.

But it's trying to find file in sys64/**bar**/config.conf

I placed it there now getting this
Loading: libsysbar.so
Key 'position' not found in section 'main'
Key 'size' not found in section 'main'
Key 'verbose' not found in section 'main'
Key 'main-monitor' not found in section 'main'
Key 'm_start' not found in section 'main'
Key 'm_center' not found in section 'main'
Key 'm_end' not found in section 'main'

Also I manually generated shared libraries and loading them with LD_LIBRARY_PATH since makefile is not handling it.

**Comment by System64fumo** [comment]
Ah the bar one is for sysbar
sysshell loads every lib specified in it's main config
If you have `load=bar,board,hud,ect..` in your main section it will look for sysbar's config file

**Comment by WHO53** [comment]
So, what should I do?
I am little confused here .

**Comment by who53** [comment]
Ah, understood
Nice Project, Sad it needs some more work to work for me. My device is rather peculiar, the shader compilation is failing. Not your fault :P

**Comment by System64fumo** [comment]
I'd suggest using GSK_RENDERER=cairo
You don't need hardware acceleration for most stuff

**Comment by who53** [comment]
Yeah tried it already, it doesn't work as intended.
